create database sys_db
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

use sys_db;

CREATE TABLE user_tbl (
    USER_ID INT NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(64) NOT NULL,
    USER_PASSWORD VARCHAR(32) NOT NULL,
	EMAIL VARCHAR(64),
    USER_FIRST_LOGIN INT NOT NULL,
	USER_LAST_LOGIN_DATE DATETIME NOT NULL,
	USER_STATUS INT NOT NULL,
    PRIMARY KEY (USER_ID)
)  ENGINE=INNODB;

CREATE TABLE role_tbl (
    ROLE_ID INT NOT NULL AUTO_INCREMENT,
    ROLE_NAME VARCHAR(20) NOT NULL,
    ROLE_DESC VARCHAR(30),
    PRIMARY KEY (ROLE_ID)
)  ENGINE=INNODB;

CREATE TABLE auth_tbl (
    AUTH_ID INT NOT NULL AUTO_INCREMENT,
    AUTH_NAME VARCHAR(30) NOT NULL,
    AUTH_DESC VARCHAR(30),
	AUTH_PARAM VARCHAR(50) not null,
    PRIMARY KEY (AUTH_ID)
)  ENGINE=INNODB;

CREATE TABLE user_role_tbl (
	USER_ROLE_ID INT NOT NULL AUTO_INCREMENT,
    ROLE_NAME VARCHAR(20) NOT NULL,
    USER_NAME VARCHAR(64) NOT NULL,
    PRIMARY KEY (USER_ROLE_ID)
)  ENGINE=INNODB;

CREATE TABLE role_auth_tbl (
    ROLE_AUTH_ID INT NOT NULL AUTO_INCREMENT,
    ROLE_NAME VARCHAR(20) NOT NULL,
    AUTH_NAME VARCHAR(30) NOT NULL,
    PRIMARY KEY (ROLE_AUTH_ID)
)  ENGINE=INNODB;

CREATE TABLE sys_type_tbl (
	TYPE_ID INT NOT NULL AUTO_INCREMENT,
	SYS_TYPE_NAME VARCHAR(16) NOT NULL,
	SYS_TYPE_DESC VARCHAR(100),
	PRIMARY KEY (TYPE_ID)
) ENGINE=INNODB;

CREATE TABLE sys_info_tbl (
    SYS_ID INT NOT NULL AUTO_INCREMENT,
    SYS_LABEL VARCHAR(20) NOT NULL,
    SYS_TYPE VARCHAR(16) NOT NULL,
    SYS_PN VARCHAR(10) NOT NULL,
    SYS_SN VARCHAR(10),
    SP_MAC VARCHAR(20) NOT NULL,
    SP_IP VARCHAR(16) NOT NULL,
    SP_TELNET_IP VARCHAR(16) NOT NULL,
    SP_TELNET_PORT VARCHAR(6) NOT NULL,
    SYS_STATE INT NOT NULL,
    POSITION VARCHAR(10),
    LOG VARCHAR(256),
    PRIMARY KEY (SYS_ID)
)  ENGINE=INNODB;

CREATE TABLE res_tbl (
    RES_ID INT NOT NULL AUTO_INCREMENT,
	SYS_ID INT NOT NULL,
	USER_ID INT NOT NULL,
    RES_DATE DATETIME NOT NULL,
    RES_HOUR INT NOT NULL,
    PRIMARY KEY (RES_ID)
)  ENGINE=INNODB;

CREATE TABLE access_record_tbl (
	RECORD_ID INT NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(50) NOT NULL,
    ACCESS_TYPE VARCHAR(30) NOT NULL,
    ACCESS_TIME DATETIME NOT NULL,
    ACCESS_IP VARCHAR(45) NOT NULL,
    PRIMARY KEY(RECORD_ID)
) ENGINE=INNODB;

CREATE TABLE operation_record_tbl (
	RECORD_ID INT NOT NULL AUTO_INCREMENT,
	USER_NAME VARCHAR(50) NOT NULL,
	OPERATION_NAME VARCHAR(30) NOT NULL,
	OPERATION_TIME DATETIME NOT NULL,
	OPERATION_RESULT VARCHAR(15) NOT NULL,
	PRIMARY KEY(RECORD_ID)
) ENGINE=INNODB;


INSERT INTO `user_tbl` (
    USER_NAME,USER_PASSWORD,EMAIL,USER_FIRST_LOGIN,USER_LAST_LOGIN_DATE,USER_STATUS
) VALUES 
    ('root', 'shsp', 'bin.wang@oracle.com', 1, '2017-12-04 00:00:00', 1),
	('binwan', 'abc123', 'bin.wang@oracle.com', 1, '2017-12-22 00:00:00', 1);

INSERT INTO role_tbl (
	ROLE_NAME, ROLE_DESC
) VALUES 
	('admin', 'system administrator'),
	('superUser', 'super user');

INSERT INTO user_role_tbl (
	ROLE_NAME, USER_NAME
) VALUES 
	('superUser', 'alex'),
	('admin', 'root');